# Generated by Django 4.1.7 on 2023-05-21 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_filiere'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, unique=True, verbose_name='libelle')),
                ('ufr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ufr', verbose_name='Ufr')),
            ],
            options={
                'verbose_name_plural': 'Specialité',
            },
        ),
    ]
