# Generated by Django 4.1.7 on 2023-05-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_specialite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=150, unique=True, verbose_name='libelle')),
            ],
            options={
                'verbose_name_plural': 'Niveau',
            },
        ),
    ]
