# Generated by Django 4.1.7 on 2023-05-21 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niveau_Specialite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Specialite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.specialite', verbose_name='Specialité')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.niveau', verbose_name='Niveau')),
            ],
            options={
                'verbose_name_plural': 'Niveau_Specialité',
            },
        ),
    ]
