# Generated by Django 4.1.7 on 2023-05-22 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_niveau_specialite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=60, unique=True, verbose_name='Libelle')),
            ],
            options={
                'verbose_name_plural': 'Ville',
            },
        ),
        migrations.RenameModel(
            old_name='Niveau_Specialite',
            new_name='NiveauSpecialite',
        ),
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=60, unique=True, verbose_name='libelle')),
                ('Ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.ville', verbose_name='Ville')),
            ],
            options={
                'verbose_name_plural': 'Ville',
            },
        ),
    ]
