# Generated by Django 4.1.7 on 2023-05-22 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_ville_rename_niveau_specialite_niveauspecialite_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commune',
            options={'verbose_name_plural': 'Commune'},
        ),
    ]
