# Generated by Django 4.1.7 on 2023-05-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='date_de_naissance',
            field=models.DateField(max_length=20, verbose_name='Date de Naissance'),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='lieu_de_naissance',
            field=models.CharField(max_length=20, verbose_name='Lieu de Naissance'),
        ),
    ]
