# Generated by Django 4.1.7 on 2023-05-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_alter_etudiant_date_de_naissance_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='niveauspecialite',
            options={'verbose_name_plural': 'Niveau et Specialité'},
        ),
    ]
