# Generated by Django 4.1.7 on 2023-05-24 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_specialite1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialite',
            name='ufr',
        ),
        migrations.AddField(
            model_name='specialite',
            name='filiere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.filiere', verbose_name='Filiere'),
        ),
        migrations.DeleteModel(
            name='Specialite1',
        ),
    ]
