# Generated by Django 4.1.7 on 2023-05-30 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_remove_specialite_ufr_specialite_filiere_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='carte_cni',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to='cni', verbose_name='Carte NCI'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='carte_etudiant',
            field=models.FileField(blank=True, max_length=50, null=True, unique=True, upload_to='', verbose_name="Carte d'etudiant"),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, max_length=150, verbose_name="Date D'identification"),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='numero_cni',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='N°CNI'),
        ),
    ]
